### ISSUE TITLE
[Bug]: okhttp3 exception

### ISSUE THREAD

**Issue by BenFredjSkander** [OneSignal/onesignal-java-api#10]
### What happened?

The latest version of the API library throws an exception when creating a notification  with this line
`CreateNotificationSuccessResponse result = apiInstance.createNotification(notification);
`

    @Value(value = "${app.onesignal.appid}")
    private static String appId;

    @Value(value = "${app.onesignal.restapikey}")
    private static String appKeyToken;

    @Value(value = "${app.onesignal.userauthkey}")
    private static String userKeyToken;

    private static Notification createNotification() {
        Notification notification = new Notification();
        notification.setAppId(appId);
        List<String> segments = new ArrayList<>();
        segments.add("Subscribed Users");
        notification.includedSegments(segments);
        notification.setIsAndroid(true);
        notification.setAndroidAccentColor("FFFFC733");
        notification.smallIcon("ic_stat_onesignal_default");
        StringMap contentStringMap = new StringMap();
        contentStringMap.en("Test body");

        StringMap headinMap = new StringMap();
        headinMap.en("Title");

        notification.setContents(contentStringMap);
        notification.setHeadings(headinMap);
        return notification;
    }

    public void send(){
        // Setting up the client
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        HttpBearerAuth appKey = (HttpBearerAuth) defaultClient.getAuthentication("app_key");
        appKey.setBearerToken(appKeyToken);
        HttpBearerAuth userKey = (HttpBearerAuth) defaultClient.getAuthentication("user_key");
        userKey.setBearerToken(userKeyToken);
        DefaultApi apiInstance = new DefaultApi(defaultClient);

        // Setting up the notification
        Notification notification = createNotification();

        try {
            CreateNotificationSuccessResponse result = apiInstance.createNotification(notification);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling DefaultApi#createNotification");
            System.err.println("Status code: " + e.getCode());
            System.err.println("Reason: " + e.getResponseBody());
            System.err.println("Response headers: " + e.getResponseHeaders());
            e.printStackTrace();
        }
    }

### Steps to reproduce?

```Markdown
1. clone the repository
2. run mvnw clean install
3. add the maven dependency to my Spring project v 2.6.7
4. execute the above method
```

### What did you expect to happen?

expected the API to return HTTP 200

### Relevant log output

```Shell
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at com.onesignal.client.ApiClient.serialize(ApiClient.java:900)
	at com.onesignal.client.ApiClient.buildRequest(ApiClient.java:1151)
	at com.onesignal.client.ApiClient.buildCall(ApiClient.java:1103)
	at com.onesignal.client.api.DefaultApi.createNotificationCall(DefaultApi.java:434)
	at com.onesignal.client.api.DefaultApi.createNotificationValidateBeforeCall(DefaultApi.java:446)
	at com.onesignal.client.api.DefaultApi.createNotificationWithHttpInfo(DefaultApi.java:483)
	at com.onesignal.client.api.DefaultApi.createNotification(DefaultApi.java:465)
	at com.exemple.service.impl.PushTest.send(PushTest.java:74)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Qleoz12** [comment]
@BenFredjSkander i checked the error and I realized is a dependecy problem, I keep diggin and I find this 
https://lightrun.com/answers/instagram4j-instagram4j-not-compatible-with-quarkus-javalangnosuchmethoderror-okhttp3requestbody-okhttp3requestbodyc, it works for me just  after onesignal-java-client

`<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>3.14.9</version>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>onesignal-java-client</artifactId>
			<version>1.0.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.7.2</version>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp-urlconnection</artifactId>
			<version>4.7.2</version>
		</dependency>`

**Comment by KrunchMuffin** [comment]
What is the status on this? We can't move forward.
