### ISSUE TITLE
[question]: how show or access to swagger docs

### ISSUE THREAD

**Issue by Qleoz12** [OneSignal/onesignal-java-api#12]
### How can we help?

i checked the code from onesignal-java-api has the swagger annotations, I would like to know how check or access to documentation, non java documentation.?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @Qleoz12 , thanks for the question. All the documentation available at https://documentation.onesignal.com/. At the same time swagger documentation available when hovering over the method name in the IntelliJ Idea.
