### ISSUE TITLE
[Bug]: There is an interesting bug on viewdevices api

### ISSUE THREAD

**Issue by betul-sahin** [OneSignal/onesignal-java-api#16]
### What happened?

When i entered my apikey with more than one character, api returns success. 

For example:
my app id: correct
my api key: correctx

(I put my api key plus x)

### Steps to reproduce?

```Markdown
1. Run this api with below info. https://onesignal.com/api/v1/players?app_id=<my-app-id>&limit=300&offset=0
2. Enter correct app id
3. Enter correct api key + one character
4. And run
```

### What did you expect to happen?

It should an error soemthing like below:
 "Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> or Bearer token=\"<YOUR-REST-API-KEY-HERE>\" with a valid REST API key."

![image](https://user-images.githubusercontent.com/66464074/189417344-ba94abd4-f5be-42fa-8925-64fdef68083d.png)
![image](https://user-images.githubusercontent.com/66464074/189417362-d80ac491-3e57-40e5-a0de-ecfb7b1e1dd4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hey @betul-sahin, thanks for reporting. We'll look into this. 
In the meantime, since you must have the entire API key correct before adding an additional character, this is still secure.

**Comment by kesheshyan** [comment]
Hey @betul-sahin, thanks for point this out. As @nan-li said, since you have to enter the entire api key it is still secure. Also this is not an issue of the Java API client but rather a server API feature.

**Comment by betul-sahin** [comment]
Thank you @nan-li and @kesheshyan 

Should i move this bug which place?
