### ISSUE TITLE
[question]:  How to get the App_key, user_key_token, app_token?

### ISSUE THREAD

**Issue by EviCoach** [OneSignal/onesignal-java-api#4]
### How can we help?

How to get the App_key, user_key_token, app_token?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @EviCoach ,

Thanks for asking ! We will be adding this info to the README later. But for now, please:
- to get **APP_ID**:
Go to the `https://app.onesignal.com/apps/` page, find your application and open it. You can fin the APP ID in the URL.
- to get **APP_KEY_TOKEN**:
Go to the `https://app.onesignal.com/apps/<YOUR_APP_ID>/settings/keys_and_ids` page.
If you don't have a Rest API Key already generated - please generate a new one by clicking a *Generate New API Key* button.
- to get **USER_KEY_TOKEN**:
Go to the `https://app.onesignal.com/profile` page and scroll down to the *User Auth Key* section.
If you don't have an AUTH KEY already generated - please generate a new one by clicking a *Generate New User Auth Key* button.

Hopefully this helpls!
