### ISSUE TITLE
[question]: 

### ISSUE THREAD

**Issue by StevenNdaye** [OneSignal/onesignal-java-api#6]
### How can we help?

Hi,

How does one pass the filter object to the notification?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @StevenNdaye, thanks for asking. You will need to create a specific **segment** of users and apply filter to it. You can do it through the dashboard of your application https://app.onesignal.com/apps/ or you can do it programmatically like this:
```java
private static Segment createSegment(String name) {
      // Setting up the filter
      Filter filter = new Filter();
      filter.setField("session_count");
      filter.setRelation(Filter.RelationEnum.GREATER_THAN);
      filter.setValue("1");
      FilterExpressions filterExpressions = new FilterExpressions(filter);

      // Setting up the segment
      Segment segment = new Segment();
      segment.setName(name);
      segment.setFilters(Arrays.asList(new FilterExpressions[] {filterExpressions}));

      return segment;
  }
  ```
Then you need to specify this segment when sending a notification:
```java
notification.setIncludedSegments(Arrays.asList(new String[]{"Your segment name"}));
```

**Comment by StevenNdaye** [comment]
Thank you very much. This works as expected.
